### ISSUE TITLE
Android Constraints in default views are wrong

### ISSUE THREAD

**Issue by Cheesebaron** [Plac3hold3r/MvxScaffolding#106]
`fragment_main` and `fragment_settings` both use ConstraintsLayout and attempt to use them. However, the constraints are not really taking effect, because width and height are set to `wrap_content`. If it is fully constrained `0dp` should be used instead.

**Comment by Plac3hold3r** [comment]
Very true. When I first tried out `ConstraintsLayout`  kept using traditional layout sizing like `wrap_content`. Thanks for point this out.
