### ISSUE TITLE
[Feature Request] Master-Detail View or any other layout

### ISSUE THREAD

**Issue by orestesgaolin** [Plac3hold3r/MvxScaffolding#26]
Hi, first of all thanks for the great tool for creating the basic boilerplate for MvvmCross application. Works perfectly both on Windows and Mac.

I wonder whether it would be possible to add option to create basic Master-Detail view with menu drawer or any other typical layout - e.g. bottom/top tabs navigation.

**Comment by Plac3hold3r** [comment]
Hi @orestesgaolin, thank you for your feedback :)

This is definitely something that I would like to add to the templates. I'm currently exploring ways to add optional additional features, like the layout options you suggested, without adding too much maintenance overhead in terms of the increase in permutation within the templates.

With the release of support for MvvmCross 6.0.0 now done. Future short terms feature I would like to explore are (in order of current priority)

- Creating a Visual Studio for Mac add-in
- Add additional template layout options
- Add support for selecting MvvmCross plugins

**Comment by Plac3hold3r** [comment]
In terms of the Visual Studio for Mac add-in, I have not created one before so I currently playing around and figuring out how it all works. So depending on how it goes I may put it on hold and push through the layout changes instead.

I have an idea for adding additional layout options. I would just need to figure out a pattern for Xamarin Forms, I'm more familiar with Xamarin native. 

For adding support for common MvvmCross plugins should be fairly straight forward. Must of the work would be around adding the UI elements to the wizard for Visual Studio.

**Comment by Plac3hold3r** [comment]
The release of v0.13.0 includes the start of adding support for additional template option. Currently MvxNative support Android and iOS Navigation menu template options.
