### ISSUE TITLE
Build of UWP project after project create generates Xaml Internal error WMC9999

### ISSUE THREAD

**Issue by jraldrin** [Plac3hold3r/MvxScaffolding#342]
Hi,

When I attemp to build the UWP app after creating solution I get the following error:>

C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(375,5): Xaml Internal Error error WMC9999: Sequence contains no elements

All I did was make the UWP project the startup and then did a build.

Thanx for any help

jra

**Comment by Plac3hold3r** [comment]
Hi, @jraldrin which template where you using? Forms or native? Additionally, which scaffold type did you choose, blank, single view or navigation menu?

**Comment by jraldrin** [comment]
Sorry for leaving out the details.

I'm using version 0.25
I created a Forms solution with ios, android, and uwp.
I chose the blank scaffold.
Uwp min sdk was set to 1809 October 2018.
Android build and ran fine.  Haven't tried IOS.

**Compile error went away when I changed the min sdk back to default (Fall Creators Update 16299)**

Thanx

John A

**Comment by jraldrin** [comment]
Looks like when I changed the min sdk version to 1809 it made the Target version less than the min version.  
From the project file
  <TargetPlatformVersion>10.0.17134.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

Sorry to bother u, thanx for quick response.  I really like your tool.

John A

**Comment by Plac3hold3r** [comment]
Thanks @jraldrin , busy looking into this now as well. I think the `TargetPlatformMinVersion` MvxScaffolding is using for the `1809 October` update is wrong. I will confirm shortly.

**Comment by Plac3hold3r** [comment]
@jraldrin I can confirm, as you noted, is that the template's default target platform version is one version behind the latest. I'll update this now, and do a patch release. Thanks for logging the issue.
