### ISSUE TITLE
Failed to start Wizard - Forms

### ISSUE THREAD

**Issue by prom3theu5** [Plac3hold3r/MvxScaffolding#358]
Exception on clicking create new project:
initialization of mahapps.metro.controls.windowcommands threw exception

VS: 15.9.9

-

Edit - Works when running VS as Admin

**Comment by Plac3hold3r** [comment]
Thanks, @prom3theu5 . I'm trying to replicate this when running VS, not as Admin, but all seems fine. Could you give any more information? Is your Visual Studio installed in a non-default location? Is the location you are trying to create the project in a privileged directory? 

Just to confirm this is happening when starting the wizard?

**Comment by prom3theu5** [comment]
Hi
That’s right!
After selecting new project -> Xamarin forms template, I get the error dialogue instead of the wizard 
It’s on 15.9.9, previous update before current (been waiting on 2019s release tomorrow before I update on my laptop where the issue is occurring)
Windows 10:1809

VS 2017 installed in the default location. However it was originally a 2017 community install that I upgraded to enterprise last year when I renewed MSDN

Location I’m creating the project is just a folder on a drive I use for local git repos. 
However I’ve just tried SpecialFolder desktop and appdata

**Comment by prom3theu5** [comment]
Sorry, fat fingers lol. Hit close and comment instead of comment on mobile :P

**Comment by Plac3hold3r** [comment]
No worries @prom3theu5 . Thanks for the additional detail.
I'll have another look over the weekend to see if I can see what is happening. Is there any more details shown than "initialization of mahapps.metro.controls.windowcommands threw exception"?

In terms of 

> ...during nuget restore it also crashes VS. When reloading the created project everything is fine...

This is an interesting issues that only occur in the Android and iOS project, UWP is fine. I have logged a ticket [here](https://developercommunity.visualstudio.com/content/problem/484336/xamarin-project-failing-to-load-correctly-when-usi.html) with Visual Studio, as I don't have access to the doc/code to figure out what Xamarin project load is missing which causes the crash/reload.

> ...offer plugin installation, common libraries such as refit and akavanche...

This has been something I have thought about and been on the fence with. On the one hand, it makes it easy as part of the project creation to choose plugin/packages, however, MvxScaffolding would need to constantly update these dependencies as well as decided which packages to support. On the other with package reference install via NuGet packages is now super quick and allows for the latest versions. With the downside being, you have to add it after project generation.

**Comment by Plac3hold3r** [comment]
@prom3theu5 are you still experiencing this issue when using Visual Studio 2019?

**Comment by Plac3hold3r** [comment]
@prom3theu5 I'm going to close this issue if you are still experiencing an issue let me know, you can also check out #408 which may have been a similar issue.
