### ISSUE TITLE
Project template fails to create project on VS 15.7.1

### ISSUE THREAD

**Issue by lukepothier** [Plac3hold3r/MvxScaffolding#40]
I'm not able to create a new project using the template in Visual Studio v15.7.1. After selecting the project template and entering a project name/path, Visual Studio raises an error and the project wizard doesn't appear.

The error message given by Visual Studio is:

> Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

![mvxscaffolding_1](https://user-images.githubusercontent.com/7534682/40012379-c63fcf66-57aa-11e8-9397-7507119f3fe0.png)
![mvxscaffolding_2](https://user-images.githubusercontent.com/7534682/40012388-cbd3bf32-57aa-11e8-8471-1819ce78d272.png)

**Comment by Plac3hold3r** [comment]
Thanks, @lukepothier can you try updating/installing version 0.10.0. It contains a workaround for the missing Newtonsoft.Json package reported by Visual Studio 2017.

**Comment by lukepothier** [comment]
Yup, all good on 0.10.0 👍
