### ISSUE TITLE
Not able to update App Icon in iOS

### ISSUE THREAD

**Issue by ram-spurtree** [Plac3hold3r/MvxScaffolding#616]
Below issue i am getting while running the app
 Error: File not found: /Users/ABC/Documents/Projects/XYZ/XYZ/src/XYZ.iOS/Resources/Media.xcassets/AppIcons.appiconset/Icon-87.png (XYZ.iOS)

Can some help me to resolve this? Thanks in advance.

Thanks,
Ram

**Comment by Plac3hold3r** [comment]
Hi @ram-spurtree it would seem you are missing an App Icon image at the 87px size (used for the settings icon). 
Which template and scaffold type were you using when you encounter this issue?

**Comment by ram-spurtree** [comment]
@Plac3hold3r , Thanks for the reply. I fixed this issue. When I am passing the images to the AppIcon assets, the names are not replaced in XXX.iOS.csproj
