### ISSUE TITLE
Unable to add NuGet package MvvmCross.Binding

### ISSUE THREAD

**Issue by ram-spurtree** [Plac3hold3r/MvxScaffolding#661]
Hi Team,

We are trying to use **MvxImageViewLoader** in **MvxTableViewCell**. But we are not able to use this until and unless we add NuGet package MvvmCross.Binding.

But after adding MvvmCross.Binding, we are getting the below an issue 

XXX.iOS/Linker/LinkerPleaseInclude.cs(29,29): Error CS0433: The type '**MvxTaskBasedBindingContext**' exists in both '**MvvmCross.Binding**, Version=5.7.0.0, Culture=neutral, PublicKeyToken=null' and '**MvvmCross**, Version=6.3.1.0, Culture=neutral, PublicKeyToken=null' (CS0433) (XXX.iOS)

Thanks in advance,
Ram.

**Comment by Plac3hold3r** [comment]
Hi @ram-spurtree ,

This is not an issue with the MvxScaffolding templates. 

That being said, it seems you are trying to install a MvvmCross 5.7.0 NuGet package `MvvmCross.Binding` into a project that is using MvvmCross 6.3.1. Note `MvvmCross.Binding` was removed as part of MvvmCross 6+. Please see MvvmCross [documentation ](https://www.mvvmcross.com/documentation/upgrading/upgrade-to-mvvmcross-60?scroll=1800)for more info on the change between 5 and 6. 

Note that as part of MvvmCross 6 update `MvxImageView` (and so `MvxImageViewLoader`) was removed see the 5 to 6 [upgrade docs](https://www.mvvmcross.com/documentation/upgrading/upgrade-to-mvvmcross-60?scroll=1800#color) which describes an alternative approach.

**Comment by ram-spurtree** [comment]
Thanks for the reply @Plac3hold3r . I am new to Xamarin, so I don't know these. I will look into this.

For integrating MvvmCross, I have wasted a week's time. After doing a bit research I found your template and integrated with in 5 Mins. Thanks a lot for your efforts.
