### ISSUE TITLE
The application is in break mode

### ISSUE THREAD

**Issue by Julibazzi** [Plac3hold3r/MvxScaffolding#672]
When trying to run the newly created project Android application of type "Navigation Menu" the following error occurs: _"Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)."_

![Error](https://user-images.githubusercontent.com/16826201/67440721-1d93ca80-f5c8-11e9-83a9-5d37b7d93836.JPG)

**Extension:** MvxScaffolding v1.5.0
**Android:** 9.0 - API 28
**Visual Studio:** Visual Studio Professional 2017 - v15.9.17
**App Details:** Navigation Menu (Xamarin.Forms)

Is any other configuration required?

**Comment by Plac3hold3r** [comment]
Hi @Julibazzi, there should not be any additional configuration required. 

Could you perhaps provide the full stack trace that you get? i.e. continue after encountering the exception and share the console output.

**Comment by Julibazzi** [comment]
[ConsoleLog.txt](https://github.com/Plac3hold3r/MvxScaffolding/files/3768699/ConsoleLog.txt)

**Comment by Plac3hold3r** [comment]
Out of interest are you having a similar issue with the single view Xamarin Forms and Xamarin Native templates?

**Comment by Plac3hold3r** [comment]
@Julibazzi thanks for the update glad to hear it worked out in the end.

Thanks as well of the translations, I'll add them in the next release :)
