### ISSUE TITLE
exclamation mark before Base package name

### ISSUE THREAD

**Issue by gt4dev** [Plac3hold3r/MvxScaffolding#678]
Don't use ! in Base package name in:
- Core/ViewModels
- Platform/Views

AFAIR this name is against C# packages naming convetions and mislead developers.
BTW. I've never seen such name earlier ;]

BTW. Why there is used '!' ?

**Comment by Cheesebaron** [comment]
There are no namespaces prefixed with !. There are however folders that start with !, which is totally fine.

I would guess ! is used to make the folder appear at the top of the list.

**Comment by Plac3hold3r** [comment]
@gt4dev as commented by @Cheesebaron the purpose of `!` is only used for folder naming to insure the selected folders are placed toward to top.

**Comment by Plac3hold3r** [comment]
After thinking over this pattern I have decided it better to remove it. It always felt a bit hacky but did provide some structure in larger projects where there were a lot of different base classes and inheriting types. 

In the next release, the base classes will be in the folder root.

Thanks @gt4dev for raising this.
