### ISSUE TITLE
Intellisense/syntax color/etc. not functional after new project

### ISSUE THREAD

**Issue by tbalcom** [Plac3hold3r/MvxScaffolding#79]
I've noticed Visual Studio 2017 15.7.5 needs to be restarted to get basic functionality like syntax coloring, Intellisense, etc. to work immediately after generating a new project with MvxScaffolding. Everything works fine after I restart Visual Studio 2017.

These are the steps I used to create a new project and reproduce the error:

1. Use the MvxScaffolding MvvmCross Native template
2. Have the following Visual Studio options set:
    - Create new directory for solution.
    - Create new Git repository
3. Leave the MvxScaffolding App Defaults screen as-is. Click Next.
4. Click on iOS to deselect it. Android is the only platform selected.
5. Leave the MvxScaffolding Android screen as-is. Click Next.

Some examples of things that aren't working after generating the new solution:

1. `MvxFragmentAttribute` is not colored in a .CS file.
2. `MainContainerViewModel` is not colored in a .CS file.
3. Intellisense doesn't trigger when you type the period after `Resource.Layout`.

Building the project doesn't change anything.

**Comment by Plac3hold3r** [comment]
Thanks for reporting this. I will need to see if there is something I can do via the VSIX. I know that with the dotnet templating CLI that a template can trigger a NuGet restore. However, Visual Studio ignores this and is meant to trigger its own restore. Perhaps it may not even be related to NuGet symbols failing but some other process.

**Comment by Plac3hold3r** [comment]
@tbalcom are you running Visual Studio with the administrative right? It seems like there are issues with the `.vs` cache folder breaking symbol loading.

**Comment by tbalcom** [comment]
I wasn't running Visual Studio as admin.

**Comment by Plac3hold3r** [comment]
@tbalcom are you still experiencing this issue in the latest version of Visual Studio?

**Comment by tbalcom** [comment]
MvxScaffolding generates a project for me but Visual Studio crashes before I can verify if Intellisense, syntax coloring, etc is working. Is there any log file I can share, or something I can do to help understand why VS is crashing? This is happening with Visual Studio 2017 15.9.9 on Windows 10 1809.

**Comment by Plac3hold3r** [comment]
You can see the issue I logged with Visual Studio [here](https://developercommunity.visualstudio.com/content/problem/484336/xamarin-project-failing-to-load-correctly-when-usi.html). It only occurs with the Android and iOS project types (i.e. Xamarin).

**Comment by Plac3hold3r** [comment]
@tbalcom from my testing with the latest Visual Studi 2019. The crash issue/restart of VS and the symbol loading issue seems to be resolved. Let me know what your experience is like when you upgrade Visual Studio 2019.

**Comment by Plac3hold3r** [comment]
I'm going to close this issue. 
It seems to be resolved with Visual Studio 2019. Let me know if you are still experiencing this issue.
