### ISSUE TITLE
Can not create any project

### ISSUE THREAD

**Issue by var-seven** [Plac3hold3r/MvxScaffolding#791]
Visual Studio 2019 (Version 16.6.5)
.NET Framework 4.8.03752 
.NET Core SDK 3.1.302

I installed the template from the marketplace and try to create a new "MvxScafolding MvvmCross Forms" project. 
But if I click "Done" after setup the project, I only get the following error message

![image](https://user-images.githubusercontent.com/58722733/88340095-718c3500-cd3b-11ea-8e4f-a29296a72ecc.png)

Of course I tried to set this options, but it doesn't matter if I check the option or not. Furthermore I searched and tried some of the solutions I found, but none of them helped. 

Maybe you have an idea what's going wrong? Thx.

**Comment by Plac3hold3r** [comment]
Thank @var-seven for reporting this. I'm getting the same behaviour. As there have been no changes to MvxScaffolding template creation flow, I believe the issue may be a change in the latest versions of Visual Studio. Will need to see what I can find out.

**Comment by muri61** [comment]
Unfortunately, the same goes for me as well.

Microsoft Visual Studio Professional 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.04084

**Comment by gocmenali** [comment]
i'm getting same error message, i tried to check "use preview of ..." option, but nothing changed
Microsoft Visual Studio Community 2019
Version 16.6.3

**Comment by Plac3hold3r** [comment]
I have reported the issue to the VS team via developer community, [link](https://developercommunity.visualstudio.com/content/problem/1124689/project-template-not-generating-in-latest-version.html).

**Comment by Jose-Develaw** [comment]
> i'm getting same error message, i tried to check "use preview of ..." option, but nothing changed
> Microsoft Visual Studio Community 2019
> Version 16.6.3

Same for me with 16.6.5

**Comment by Plac3hold3r** [comment]
In the meantime, while we wait for feedback from the VS team as to the changes required to support the latest VS builds, you can use the dotnet command-line tool version of MvxScaffolding. It has all the same features as the VS 2019 UI wizard version.

See docs on how to [install ](https://github.com/Plac3hold3r/MvxScaffolding#dotnet-cli) and the [commands](https://github.com/Plac3hold3r/MvxScaffolding/blob/develop/docs/template_dotnet_cli.md) usage.

**Comment by Plac3hold3r** [comment]
Turns out it was an issue in the template, after all, a duplicate key.

**Comment by Plac3hold3r** [comment]
Version 1.9.1 released with the fix.
