### ISSUE TITLE
[Android] Both AXML and XML files are being generated

### ISSUE THREAD

**Issue by tbalcom** [Plac3hold3r/MvxScaffolding#80]
Both AXML and XML files are being generated when creating a new solution using the MvxScaffolding MvvmCross Native Template using the default settings. The AXML files are present in both the solution and the file system. The XML files are present in the solution but not the file system, so Visual Studio shows a yellow triangle next to these files. Clicking the file shows the error:

> The item 'activity_main_container.xml' does not exist in the project directory. It may have been moved, renamed, or deleted.

**Comment by Plac3hold3r** [comment]
Hey @tbalcom , thanks for reporting this. I had looked at the code, it seems I forgot to update the csproj template keys after I made the switch to use an options drop-down approach for specifying Android layouts. 

I should be able to get the fix into the next release.

**Comment by Plac3hold3r** [comment]
The issue should be resolved in 0.13.0 release.
