### ISSUE TITLE
Toolbar in Native/NM/BaseActivity is not cached

### ISSUE THREAD

**Issue by Cheesebaron** [Plac3hold3r/MvxScaffolding#91]
If you look at https://github.com/Plac3hold3r/MvxScaffolding/blob/master/src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/Views/!Base/BaseActivity.cs#L22 calling the getter on the `Toolbar` property will be super expensive, since `FindViewById` would need to traverse the view hierarchy for every call.

Consider caching it or change the expression body to `{ get; } = FindViewById<Toolbar>(...);`

**Comment by Plac3hold3r** [comment]
Good point. I'll update the property to cache the `Toolbar`.

**Comment by Cheesebaron** [comment]
I guess this can be closed 👍
