### ISSUE TITLE
MvvmCross 8

### ISSUE THREAD

**Issue by SBLeJa** [Plac3hold3r/MvxScaffolding#977]
Any ETA for MvvmCross 8 support?

**Comment by Plac3hold3r** [comment]
Hopefully in the next few days. 

I have just merged in the latest v8.0.2 dependencies in to develop branch. I just need to validate all is still working as expected.

**Comment by Plac3hold3r** [comment]
@SBLeJa version 1.14.0 release with Mvx 8 support 😀
