### ISSUE TITLE
LinkerPleaseInclude.cs UISearchBar addition?

### ISSUE THREAD

**Issue by Hackmodford** [Plac3hold3r/MvxScaffolding#994]
Does this need to be added to the linkerPleaseInclude.cs file?

```
public void Include(UISearchBar searchBar)
{
   searchBar.Text = $"{ searchBar.Text }";
   searchBar.TextChanged += (sender, e) => searchBar.Text = "";
   searchBar.CancelButtonClicked += (s, e) => searchBar.Text = $"{ searchBar.Text }";
}
```

**Comment by Plac3hold3r** [comment]
Hi @Hackmodford, it can be added. I have no issue with including this change. Would you like to do a PR for it?

**Comment by Hackmodford** [comment]
I will create a PR. I just wanted to confirm it fixed a crash for me first. It did.

**Comment by Hackmodford** [comment]
PR created

**Comment by Plac3hold3r** [comment]
Thanks, I will include this in the next build.
