### ISSUE TITLE
Overflow is hidden with french language

### ISSUE THREAD

**Issue by varKeytrap** [Plac3hold3r/MvxScaffolding#996]
![image](https://user-images.githubusercontent.com/17864005/132304453-fd38b3a6-89ef-402f-86f6-caa8b7f2e535.png)

**Comment by Plac3hold3r** [comment]
Thanks @varKeytrap for reporting this.

**Comment by Plac3hold3r** [comment]
Confirming the fix with additional language. The next release should resolve this issue :)

![image](https://user-images.githubusercontent.com/13716738/132409817-1f18762c-d27a-4638-b088-a8e5c4c024bb.png)

**Comment by varKeytrap** [comment]
Thank you !
